### ISSUE TITLE
Instructions for building

### ISSUE THREAD

**Issue by Russell91** [thestinger/rust-snappy#3]
This page is referenced from the main rust tutorial on ffi, but there are no instructions on how to get a minimal version compiled. Can you add a few commands to the README that would show how to do this?

**Comment by wuranbo** [comment]
@Russell91 I make a PR https://github.com/rust-lang/rust/pull/34799. I test the code working.

**Comment by wuranbo** [comment]
And I saw that https://github.com/thestinger/rust-snappy/pull/2/files looks maybe better?
